---
- name: Perform DNF system update
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Check if we need a reboot
  ansible.builtin.command: dnf needs-restarting -r
  register: needs_restarting
  changed_when: needs_restarting.rc == 1
  notify: We need to reboot