---
- name: Insights Check In
  hosts: all
  tasks: 

    - name: Status Check
      block:
        - name: Status Check
            ansible.builtin.shell:
                cmd: /usr/bin/insights-client --status
                         
      rescue:
        - name: Register on failure
            ansible.builtin.shell:
                cmd: /usr/bin/insights-client --register
