---
- name: My first play
  hosts: satellite.o.rm
  tasks:
          - name: Ping my hosts
            ansible.builtin.ping:
          - name: Print message
            ansible.builtin.debug:
                    msg: Hello world
