---
- name: Publish Content View
  hosts: localhost
  connection: local
  tasks:
    - name: Create a filter
      redhat.satellite.content_view_filter:
        username: "{{ sat_user }}"
        password: "{{ sat_password }}"
        server_url: "{{ sat_url }}"
        name: Make Old Stuff
        organization: "{{ rh_org }}"
        content_view: RHEL 9
        filter_type: erratum
        inclusion: true

    - name: Create a filter rule
      redhat.satellite.content_view_filter_rule:
        username: "{{ sat_user }}"
        password: "{{ sat_password }}"
        server_url: "{{ sat_url }}"
        name: Make Old Stuff
        organization: "{{ rh_org }}"
        content_view: RHEL 9
        content_view_filter: "Make Old Stuff"
        date_type: updated
        end_date: "2025-12-31"

    # - name: Publish a new version of a content view
    #   redhat.satellite.content_view_version:
    #     username: "{{ sat_user }}"
    #     password: "{{ sat_password }}"
    #     server_url: "{{ sat_url }}"
    #     organization: "{{ rh_org }}"
    #     content_view: RHEL 9
    #     lifecycle_environments:
    #       - Lab Production
