---
          - name: ensure pexpect is installed in the playbook python
            pip:
                name: pexpect
                state: present

          - name: Backup dhcp config
            ansible.builtin.copy:
                    src: /etc/dhcp/dhcpd.hosts
                    dest: /root/dhcpd.hosts
                    remote_src: yes
                    backup: True
            tags: prepare

          - name: Enable next version repo
            ansible.builtin.shell: subscription-manager repos --enable satellite-maintenance-{{ target_version }}-for-rhel-8-x86_64-rpms
            register: enable_repo
            changed_when: enable_repo.rc != 0
            tags: prepare

          - name: Enable maintenance module
            ansible.builtin.shell: dnf module enable satellite-maintenance:el8
            register: module_enable
            changed_when: module_enable.rc != 0
            tags: prepare

            #- name: Confirm version is available
            #ansible.builtin.shell: satellite-maintain upgrade list-versions
            #register: list_version
            #changed_when: list_version.rc == 75
            #failed_when: list_version.rc != 75 or list_version.rc != 1
            #tags: prepare

          - name: Check health
            ansible.builtin.shell: satellite-maintain upgrade check --disable-self-upgrade --target-version {{ target_version }}
            register: upgrade_check
            changed_when: upgrade_check.rc != 0
            tags: prepare

          - name: Perform upgrade
            ansible.builtin.expect: 
                command: satellite-maintain upgrade run --disable-self-upgrade --target-version {{ target_version }}
                responses: 
                    "The pre-upgrade checks indicate that the system is ready for upgrade.":
                        - "y"
            register: upgrade
            tags: upgrade


          - name: Determine Reboot
            tags: upgrade
            block:
                  - name: Check with DNF
                    ansible.builtin.shell: dnf needs-restarting --reboothint
            rescue:
                  - name: Looks like we need a reboot
                    ansible.builtin.reboot:
