---
    - name: Publish Content View 
      redhat.satellite.content_view_version:
        username: "{{ satellite_username }}"
        password: "{{ satellite_password }}"
        server_url: "{{ satellite_url }}"
        organization: "{{ satellite_org }}"
        validate_certs: "{{ satellite_validate_certs }}"
        content_view: "{{ item.name }}"
        lifecycle_environments:
          - Lab Environment
      loop: "{{ content_views_to_manage }}"
      loop_control:
        label: "Publishing {{ item.name }}"
